### ISSUE TITLE
Export to PDF permission Problems

### ISSUE THREAD

**Issue by Wintermute2k6** [Icinga/icingaweb2-module-pdfexport#31]
## Describe the bug

As it seems there is no clear distinction between the dompdf export and the pdfexport .. with user permissions.

As Admin users can always export to PDF files (Host/Services) , Restricted users can't unless you set the following Permissions on the following Modules:

Which at least for the reporting module permissions itself makes no sense ?

pdfexport
Full Module Access: no
General Module Access: yes -> must be set otherwise it will open a  "open/save-dialog" for a pdf file with 0kb which will not successfully save.

## To Reproduce

Create an Administrative User and a non-administrative user install the the pdfexport module ..

As said above administrative users an always export wherever they are, non-admin users will fail to export to pdf with an 0 kb pdf file either in the reports or in the host/service view.

## Expected behavior

PDF export should work even with an non-administrative user as it is given on the export options by default 

## Screenshots

<img width="1054" alt="Screen Shot 2021-02-09 at 2 22 44 PM" src="https://user-images.githubusercontent.com/7203835/107369927-9e8b1400-6ae2-11eb-8c85-cc25e0248ba5.png">

## Your Environment

* Module version: 
```
pdfexport      0.9.1     enabled   PDF Export via Google Chrome/Chromium
```
* Icinga Web 2 version and modules (System - About): latest Icinga Web 2 2.8.2
* Web browser and version: latest Firefox 85 and latest Chrome 88
* Icinga 2 version used (`icinga2 --version`): 2.12.3
* Server operating system and version: centos 7 

Also if export is successful there is always a second page with just whitespace on it. labeled page 0

ref/NC700678

**Comment by nilmerg** [comment]
Hi,

I can't reproduce that. What I've tried is the following:

**First test**: (Expected result: Will fall back to dompdf)
* Logged in as user with no access to module pdfexport
* Module pdfexport is enabled
* Export to PDF results in a single page PDF produced by Web 2's internal export method

**Second test**: (Expected result: Will fall back to dompdf)
* Logged in as user with general access to module pdfexport
* Module pdfexport is disabled
* Export to PDF results in a single page PDF produced by Web 2's internal export method

**Third test**: (Expected result: Will use the pdfexport module)
* Logged in as user with general access to module pdfexport
* Module pdfexport is enabled
* Export to PDF results in a two pages PDF produced by the pdfexport module

Note that the PDF with two pages (instead of one as it's produced by dompdf) is specific to the pdfexport module. So it's easy to identify the two different sources this way.

As my tests show, there's no permission problem at all. If the user in question has access to the module and the module is enabled, the module's export method is used. If one of those two requirements are not met, Web 2's own export method (dompdf) is used.

Best,
Johannes

**Comment by Wintermute2k6** [comment]
ref/nc702434
